### ISSUE TITLE
Node build not working

### ISSUE THREAD

**Issue by jaymakes11** [wilsonzlin/minify-html#119]
This is the error I'm getting:

> Error: Cannot find module './index.node'

The require stack points to `/node_modules/@minify-html/node/index.js`

Seeing this on MacOS. Also seeing it in Linux (in the context of Cloudflare Pages build environment).

Node version: 16

**Comment by wilsonzlin** [comment]
What does it say when you install the package? It downloads a prebuilt binary for supported platforms, and then falls back to compiling from source, which requires Rust to be installed.

Are you on macOS ARM64? The README mentions it's only available for macOS x64. Try running `node -e 'console.log(process.platform, process.arch)'` to print the target for both your macOS and Linux environments. I can't reproduce the issue from Node.js 16 on Linux x64 with the latest package version.

**Comment by kejiweixun** [comment]
> What does it say when you install the package? It downloads a prebuilt binary for supported platforms, and then falls back to compiling from source, which requires Rust to be installed.
> 
> Are you on macOS ARM64? The README mentions it's only available for macOS x64. Try running `node -e 'console.log(process.platform, process.arch)'` to print the target for both your macOS and Linux environments. I can't reproduce the issue from Node.js 16 on Linux x64 with the latest package version.

I am on macOS ARM64, and indeed get ` Cannot find module './index.node'` error.

**Comment by jaymakes11** [comment]
> Are you on macOS ARM64?

Yes, so that does appear to be the issue on my local machine. 

How feasible is adding support for macOS ARM64? Not having macOS ARM64 support pretty much means I can't use this package (and this is a great package!), as being able to reproduce the same builds locally as in my CI setups is critical for my use cases (sometimes I don't even use a CI setup).

> Try running `node -e 'console.log(process.platform, process.arch)'` to print the target for [...] Linux environments. 

Will do this and report back (don't have the time right now).

**Comment by vinicius73** [comment]
Same problem here.

**Comment by tunetheweb** [comment]
Looks like support [was dropped with v0.10.0 due to lack of access to hardware](https://github.com/wilsonzlin/minify-html/commit/29e7b1c18705cbb534c2d8cabe11f66731524ac0. It works with v0.9.2 but that's getting old now :-(

**Comment by jono-hayward** [comment]
I'm getting the same issue on Windows x64 :/

**Comment by hoIIer** [comment]
Just ran into same problem! Was looking forward to trying this :|

**Comment by wilsonzlin** [comment]
I've managed to get cross compilation working with Node.js. Version `0.11.5` has macOS ARM64 builds; if you are free to test it out please let me know if you encounter any issues.

**Comment by AleksandrHovhannisyan** [comment]
Seeing this now myself on Node 18 for some reason overnight. But I have an x86 CPU, not ARM.
